name: code_base_provider_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_svg: ^2.0.1
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  dio: ^5.0.1
  fluttertoast: ^8.2.1
  carousel_slider: ^4.2.1
  qr_flutter: ^4.0.0
  pin_code_fields: ^7.4.0
  get_it: ^7.2.0
  flutter_slidable: ^2.0.0
  url_launcher: ^6.1.10
  image_picker: ^0.8.6+4
  cached_network_image: ^3.2.3
  flutter_linkify: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Italic.ttf
          style: italic
